[package]
name = "rss-aggregator"
version = "0.1.0"
authors = ["Eric <Fistons> <eric@pedr0.net>"]
edition = "2021"

[workspace]
members = [".", "entity"]

[dependencies]
reqwest = { version = "0.10", features = ["json", "blocking"] } # Request stuff over the web
actix-web = { version = "4"} # Serve stuff over the web
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8.17"
rss = { version = "1.10.0", features = ["validation", "atom"] }
dotenv = "0.15"
log = "0.4"
simplelog = "^0.10.0"
rust-argon2 = "0.8"
futures-util = "0.3.15"
http-auth-basic = "0.1.3"
jwt = "0.14.0"
hmac = "0.11.0"
tokio = "1"
sha2 = "0.9.5"
chrono = "0.4"
uuid = { version = "0.8.2", features = ["v4"] }
redis = { version = "0.20" }
clokwerk = "0.3.5"
sea-orm = { version = "^0", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros", "debug-print"], default-features = false }
entity = { path = "entity" }

[dev-dependencies]
actix-rt = "1"


[profile.release]
strip = true