[package]
name = "rss-aggregator"
version = "0.1.0"
authors = ["Eric <Fistons> <eric@pedr0.net>"]
edition = "2021"

[workspace]
members = [".", "entity"]

[dependencies]
reqwest = { version = "0.11", features = ["json", "native-tls-vendored"] } # Request stuff over the web
actix-web = { version = "4" } # Serve stuff over the web
actix-rt = "2.7"
actix-files = "0.6.0"
actix-xml = "0.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8.17"
feed-rs = "1.0.0"
dotenv = "0.15"
log = "0.4"
simplelog = "^0.10.0"
rust-argon2 = "0.8"
futures-util = "0.3.15"
http-auth-basic = "0.1.3"
jwt = "0.14.0"
hmac = "0.11.0"
sha2 = "0.9.5"
chrono = "0.4"
uuid = { version = "0.8.2", features = ["v4"] }
redis = { version = "0.20" }
clokwerk = "0.4.0-rc1"
diesel = { version = "1.4", features = ["postgres"] }

[dev-dependencies]
actix-rt = "2.7"


[profile.release]
strip = true
opt-level = "s"
lto = true
codegen-units = 1