[package]
name = "rss-aggregator"
version = "0.1.0"
authors = ["Eric <Fistons> <eric@pedr0.net>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.10", features = ["blocking", "json"] } # Request stuff over the web
rocket = "0.4.6" # Serve stuff over the web
serde = { version = "1.0", features = ["derive"] }
diesel = { version = "1.4.5", features = ["sqlite"] }

[dependencies.rocket_contrib]
version = "0.4.6"
default-features = false
features = ["json", "diesel_sqlite_pool"]