[package]
name = "rss-aggregator"
version = "0.1.0"
authors = ["Eric <Fistons> <eric@pedr0.net>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.10", features = ["json"] } # Request stuff over the web
actix-web = { version = "3", features = ["compress"] } # Serve stuff over the web
actix-files = "0.5"
r2d2 = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
diesel = { version = "1.4.5", features = ["sqlite", "r2d2"] }
rss = { version = "1.10.0", features = ["validation", "atom"] }
dotenv = "0.15"

[dev-dependencies]
actix-rt = "1"